### ISSUE TITLE
Feedback for “Run a Collection”

### ISSUE THREAD

**Issue by dmiles29** [usebruno/bruno-docs-legacy#147] opened 2024-11-06 16:43 UTC
I am using Runner and I am clicking the "Run with parameters" box. I am selecting my CSV file with my parameters in it.

But my parameters in the CSV file are not being used. 

What should my request look like in order for the parameters in the CSV to be used? 

Do I need to write a script?

**Comment by ganesh-bruno** [comment] 2024-11-11 08:00
Hi @dmiles29,

We're currently working on the documentation for the `Bruno Runner` feature and have created a similar issue on the main repository. You can track the progress of this issue here: [#3456](https://github.com/usebruno/bruno/issues/3456).

Since the issue is already available on the main repo, we'll be closing this one.

Thanks for your understanding!

**Comment by ganesh-bruno** [comment] 2024-11-13 07:09
Hey @dmiles29,

We've added a guide for the Bruno Runner in the [official documentation](https://docs.usebruno.com/testing/data-driven-testing). You can follow the steps there to use the Bruno Runner feature.

I’ll be closing this issue now. Feel free to reach out if you have any other issues!

**Closed as completed by ganesh-bruno** 2024-11-13 07:09 UTC
